dist: focal

git:
  submodules: false

services:
  - docker

before_install:
  - pip install yamllint==1.24.2

before_script:
  # Run shellcheck an all the scripts with sh shebang.
  - find ./scripts/ -type f -print0 |
        xargs -0 gawk '/^#!.*( |[/])sh/{printf "%s\0", FILENAME} {nextfile}' |
        xargs -0 shellcheck
  - yamllint .

script:
  - docker build -t "$DOCKER_USERNAME"/dotfiles .

after_success:
  - if [ "$TRAVIS_BRANCH" == "arch" ]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
        docker push "$DOCKER_USERNAME"/dotfiles;
    fi
