---
user_name: user
user_group: user
user_home: '{{ "~" | expanduser }}'
dotfiles_home: '{{ user_home }}/.dotfiles'
dirs:
  dotfiles_local: '{{ user_home }}/.dotfiles.local'
  dot_aws: '{{ user_home }}/.aws'
  dot_local_bin: '{{ user_home }}/.local/bin'
  dot_vim: '{{ user_home }}/.vim'
  dot_vim_ultisnips: '{{ user_home }}/.vim/ultisnips'
  dot_config_newsboat: '{{ user_home }}/.config/newsboat'
  dot_config_shell: '{{ user_home }}/.config/shell'
  dot_config_systemd: '{{ user_home }}/.config/systemd/user'
  documents: '{{ user_home }}/documents'
  documents_projects: '{{ user_home }}/documents/projects'
  documents_projects_clones: '{{ user_home }}/documents/projects/clones'
  documents_projects_forks: '{{ user_home }}/documents/projects/forks'
  documents_projects_private: '{{ user_home }}/documents/projects/private'
  documents_projects_public: '{{ user_home }}/documents/projects/public'
  downloads: '{{ user_home }}/downloads'
  downloads_bandcamp_dl: '{{ user_home }}/downloads/bandcamp-dl'
  downloads_firefox: '{{ user_home }}/downloads/firefox'
  downloads_torrents: '{{ user_home }}/downloads/torrents'
  firefox_profile: '{{ user_home }}/.mozilla/firefox/main'
  firefox_extensions: '{{ user_home }}/.mozilla/firefox/main/extensions'
  pictures: '{{ user_home }}/pictures'
  pictures_screenshots: '{{ user_home }}/pictures/screenshots'
  pictures_webcam: '{{ user_home }}/pictures/webcam'
  videos_webcam: '{{ user_home }}/videos/webcam'
  sync: '{{ user_home }}/sync'
  sync_books: '{{ user_home }}/sync/books'
  sync_zathura: '{{ user_home }}/sync/zathura'
