---
# Potentially conflicting files.
potential_conflicts:
  - '{{ user_home }}/.bashrc'
  - '{{ user_home }}/.bash_logout'
  - '{{ user_home }}/.bash_profile'
  - '{{ user_home }}/.profile'
  - '{{ user_home }}/.viminfo'

# Directory to move conflicting files into.
conflicts_dir: '{{ user_home }}/stow-conflicts'

packages:
  - aws
  - bash
  - picom
  - dunst
  - firefox
  - git
  - gtk-3.0
  - guvcview
  - i3
  - ipython
  - litecli
  - mpd
  - mpv
  - mycli
  - ncmpcpp
  - newsboat
  - pgcli
  - polybar
  - pylint
  - ranger
  - readline
  - redshift
  - rg
  - scripts
  - shell
  - sxhkd
  - sxiv
  - tmux
  - vim
  - x11
  - xdg
  - youtube-dl
  - zathura
  - zsh
